/**
 * Copyright (c) 2021 Digital Align
 * @group Constant
 * @author Digital Align Team
 * @reference
 * @description
 **/
@SuppressWarnings('PMD.AvoidGlobalModifier')
global with sharing class DealerConstants {
  //default IndustriesBusiness
  public static final String DEALER_ADMIN_CONTACT_RECORDTYPE = 'IndustriesBusiness';
  //default DealerAdmin
  public static final String DEALER_ADMIN_CONTACT_TYPE = 'DealerAdmin';
  //default Business_Account
  public static final String DEALER_ADMIN_ACCOUNT_RECORDTYPE = 'Business_Account';
  //default DealerAccount
  public static final String DEALER_ADMIN_ACOUNT_TYPE = 'DealerAccount';
  //default DealerCommunity Profile
  public static final String DEALER_ADMIN_USER_PROFILE = 'DealerCommunity Profile';
  //DoTractCustomerCommunity
  public static final String DEALER_COMMUNITY_PERMISSION_SET = 'DoTractCustomerCommunity';

  //default IndustriesBusiness
  public static final String DEALER_EMPLOYEE_CONTACT_RECORDTYPE = 'IndustriesBusiness';
  //default DealerAdmin
  public static final String DEALER_EMPLOYEE_CONTACT_TYPE = 'DealerEmployee';
  //default DealerCommunity Profile
  public static final String DEALER_EMPLOYEE_USER_PROFILE = 'DealerCommunity Profile';

  //default Dealer
  public static final String DEALER_LEAD_RECORDTYPE = 'Dealer';
  //default Working - Contacted
  public static final String LEAD_INITIAL_STATUS = 'Working - Contacted';
  //default Under Review
  public static final String LEAD_SUBMITTED_STATUS = 'Under Review';
}
