/**
 * Copyright (c) 2021 Digital Align
 * @group Constant
 * @author Digital Align Team
 * @reference
 * @description
 **/
@SuppressWarnings('PMD.AvoidGlobalModifier')
global with sharing class FinancialInstituteConstants {
  //default IndustriesBusiness
  public static final String FIN_INST_ACCOUNT_RECORDTYPE = 'IndustriesBusiness';
  //default FinancialInstituteAccount
  public static final String FIN_INST_ACOUNT_TYPE = 'FinancialInstituteAccount';
  //default IndustriesBusiness
  public static final String FIN_INST_EMPLOYEE_CONTACT_RECORDTYPE = 'IndustriesBusiness';
  //default DealerAdmin
  public static final String FIN_INST_EMPLOYEE_CONTACT_TYPE = 'FinancialInstituteEmployee';
  //default FinancialInstituteCommunity Profile
  public static final String FIN_INST_EMPLOYEE_USER_PROFILE = 'FinancialInstituteCommunity Profile';
  //deafult MintFlowEmployeeCommunity
  public static final String FIN_INST_COMMUNITY_PEMRISSION_SET = 'MintFlowEmployeeCommunity';

  //default Rejected
  public static final String LEAD_REJECTED_STATUS = 'Rejected';
}
