/**
 * Copyright (c) 2021 Digital Align
 * @group Service
 * @author Digital Align Team
 * @reference
 * @description
 **/

global enum APINames {
  DocumentScan,
  TwillioMessaging,
  SentiLink,
  SentiLinkIdCompletion,
  Geocoding,
  IdScan,
  AWSAuth,
  UiPathAddQueue,
  AtomicFIToken,
  UiPath,
  PlaidTokenExchange,
  PlaidRetrieveAuth,
  PlaidLinkToken,
  PlaidRetriveInstitue,
  DueDiligence
}
